const Strings = {
  signupTitle: "Let's get started",
  usernamePlaceholder: 'Enter your Username *',
  emailPlaceholder: 'Enter your Email id *',
  passwordPlaceholder: 'Enter your Password *',
  mobilePlaceholder: 'Enter your Mobile number *',
  signupButton: 'Sign-up',
  orContinue: 'or continue with',
  alreadyHave: 'Already have an account!',
  dontHave: "Don't have an account?",
  loginButton: 'Login',
  otpTitle: 'Enter verification code',
  otpSubTitle: 'Enter 4 digits code received on your Mobile number',
  otpSubTitleEmail: 'Enter 4 digits code received on your Email Id',
  otpButton: 'Submit',
  loginTitle: 'Sign In to Explore!',
  username: 'Username',
  mobile: 'Mobile Number',
  email: 'Email Id',
  forgot: 'Forgot Password?',
  resetTitle: 'Reset your password',
  resetButton: 'Reset Password',
  newPassword: 'Enter your New Password',
  conformPassword: 'Conform your New Password',
  yourAdded: 'Your Added Services',
  addYour: 'Add Your Services',
  noServices: 'No services are available.',
  addButton: 'Add',
  deleteButton: 'Delete',
  searchButton: 'Search',
  deleteYour: 'Delete Your Services',
  categoryPlaceholder: 'Select Category',
  subCategoryPlaceholder: 'Select Sub-Category',
  searchSubPlaceholder: 'Search Sub-Category',
  searchCatPlaceholder: 'Search Category',
  labelSubPlaceholder: 'Sub-Categories',
  notFoundText: 'Select The Category',
};

export default Strings;
